on:
  push:
    branches:
      - actions

jobs:
  build:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Save kubeconfig
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: echo $KUBE_CONFIG | base64 --decode > $GITHUB_WORKSPACE/.kubeconfig

    - name: Run Kubernetes tools
      uses: stefanprodan/kube-tools@v1
      with:
        command: |
          helmv3 repo add starkandwayne https://helm.starkandwayne.com
          helmv3 repo update
          export KUBECONFIG=$GITHUB_WORKSPACE/.kubeconfig
          echo "Test"
          cat $KUBECONFIG | sha1sum
          head -n 3 $KUBECONFIG
          kubectl get nodes
          echo "Test2"
          helmv3 -v 7 -n runbooks-staging upgrade --install runbooks starkandwayne/git-website -f $GITHUB_WORKSPACE/deployment/values.yml
          echo "Done"